### PR TITLE
Updates copyright year in the footer to current.

### PR DESCRIPTION
**Pull request by shindakun**
No related issue.

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
I always wondered if you change the date or maybe do something like . 2017-2018?

**Comment by shindakun** [comment]
I thought about just throwing some JS on there to auto-populate the year but it would look odd for those few people who don't have JS enabled. And I didn't want to overstep on my first PR.

**Comment by ardan-bkennedy** [comment]
Are you looking for projects to contribute to?

**Comment by shindakun** [comment]
Yeah, was looking for Go related projects. Have a bit of free time so I was looking for some low hanging fruit.

**Pull request closed without merging**
